version: '3.8'

services:
  app:
    build: .
    container_name: inventree-order-calculator-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Persistentes Volume für die Datenbank
